package miniprojet_lightoff;


import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import miniprojet_lightoff.CelluleLumineuse;
import miniprojet_lightoff.GrilleDeJeu;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author damie
 */
public class FenetrePrincipale extends javax.swing.JFrame {
    GrilleDeJeu grille;
    int nbcoups=0;
    GrilleDeJeu m = new GrilleDeJeu(5,5);
    private JLabel messageVictoire;
    
    /**
     * Creates new form FenetrePrincipale
     */
    public FenetrePrincipale() {// crée la grille et l'adapte en fonction des coups joués
        initComponents();
        int nbLignes = 5;
        int nbColonnes = 5;
        messageVictoire = new JLabel();
        this.grille = new GrilleDeJeu(nbLignes, nbColonnes);
        PanneauGrille.setLayout(new GridLayout(nbLignes, nbColonnes));//Crée la grille de bouton
        this.initialiserPartie();
        for (int i=0; i < nbLignes; i++) {
            for (int j=0; j < nbColonnes; j++ ) {
                CelluleGraphique bouton_cellule = new CelluleGraphique( grille.matriceCellules[i][j], 36,36);
                PanneauGrille.add(bouton_cellule); // ajout au Jpanel PanneauGrille
            }
            /*
            getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, nbColonnes * 40, nbLignes * 40));
            this.pack(); // Ajuste la taille de la fenêtre
            this.revalidate();*/
        }
        PanneaudesLignes.setLayout(new GridLayout(nbLignes, 1));//Crée la colonne de bouton pour changer les lignes de couleur
        for (int i=0; i < nbLignes; i++) {
            JButton p = new JButton();
            final int f = i;
            p.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    grille.activerLigneDeCellules(f);
                    PanneauGrille.repaint();
                    nbcoups ++;
                    jLabel2.setText("Vous avez joué " + nbcoups +" coups");
                    if (grille.cellulesToutesEteintes()){
                        afficherMessageVictoire();
                        
                    }
                    
                }
            });
            PanneaudesLignes.add(p);
        }
        PanneaudesColonnes.setLayout(new GridLayout(1, nbColonnes));//Crée la ligne de bouton pour changer les colonnes de couleur
        for (int i=0; i < nbColonnes; i++) {
            JButton p = new JButton();
            final int f = i;
            p.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    grille.activerColonneDeCellules(f);
                    PanneauGrille.repaint();
                    nbcoups ++;
                    jLabel2.setText("Vous avez joué " + nbcoups +" coups");
                    if (grille.cellulesToutesEteintes()){
                        afficherMessageVictoire();
                    }
                }
            });
        PanneaudesColonnes.add(p);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrille = new javax.swing.JPanel();
        PanneaudesLignes = new javax.swing.JPanel();
        Diag = new javax.swing.JPanel();
        btndiag1 = new javax.swing.JButton();
        PanneaudesColonnes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btndiag2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(242, 242, 20));
        setPreferredSize(new java.awt.Dimension(400, 400));

        PanneauGrille.setBackground(new java.awt.Color(0, 0, 242));
        PanneauGrille.setLayout(new java.awt.GridLayout(1, 0));

        PanneaudesLignes.setBackground(new java.awt.Color(242, 242, 2));

        javax.swing.GroupLayout PanneaudesLignesLayout = new javax.swing.GroupLayout(PanneaudesLignes);
        PanneaudesLignes.setLayout(PanneaudesLignesLayout);
        PanneaudesLignesLayout.setHorizontalGroup(
            PanneaudesLignesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanneaudesLignesLayout.setVerticalGroup(
            PanneaudesLignesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Diag.setBackground(new java.awt.Color(242, 2, 242));

        btndiag1.setText("Diag descendante");
        btndiag1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndiag1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DiagLayout = new javax.swing.GroupLayout(Diag);
        Diag.setLayout(DiagLayout);
        DiagLayout.setHorizontalGroup(
            DiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btndiag1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DiagLayout.setVerticalGroup(
            DiagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btndiag1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PanneaudesColonnes.setBackground(new java.awt.Color(242, 242, 100));
        PanneaudesColonnes.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LIGHT OFF");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(242, 0, 242));

        btndiag2.setText("diag montante");
        btndiag2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndiag2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btndiag2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btndiag2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jLabel2.setText("Nombre de coups : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Diag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanneaudesLignes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PanneauGrille, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PanneaudesColonnes, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PanneaudesColonnes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Diag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PanneauGrille, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                            .addComponent(PanneaudesLignes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(53, 53, 53))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Bouton pour changer la diagonale de couleur
    private void btndiag1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndiag1ActionPerformed
        this.grille.activerDiagonaleDescendante();
        repaint();
        nbcoups ++;
        jLabel2.setText("Vous avez joué " + nbcoups +" coups");
        if (grille.cellulesToutesEteintes()){
            afficherMessageVictoire();
        }
    }//GEN-LAST:event_btndiag1ActionPerformed
// Bouton pour changer la diagonale opposé de couleur
    private void btndiag2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndiag2ActionPerformed
       this.grille.activerDiagonaleMontante();
        repaint();
        nbcoups ++;
        jLabel2.setText("Vous avez joué " + nbcoups +" coups");
        if (grille.cellulesToutesEteintes()){
            afficherMessageVictoire();
        }
    }//GEN-LAST:event_btndiag2ActionPerformed

    
    public void initialiserPartie() {// crée aléatoirement une grille avec des pions positionnés aléatoirement
        grille.eteindreToutesLesCellules();
        grille.melangerMatriceAleatoirement(100);
    }
    
    public class CelluleGraphique extends JButton {
        int largeur; // largeur en pixel de la cellule
        int hauteur; // hauteur en pixel de la cellule
        
        CelluleLumineuse celluleLumineuseAssociee; 
        
        // constructeur (appelé depuis FenetrePrincipale)
        public CelluleGraphique(CelluleLumineuse celluleLumineuseAssociee, int l,int h) {
            this.largeur = l;
            this.hauteur = h;
            this.celluleLumineuseAssociee = celluleLumineuseAssociee;
        }
        // Methode gérant le dessin de la cellule 
        @Override
        protected void paintComponent(Graphics g) {//donne de la couleur au boutons
            super.paintComponent(g); 
            this.setText(celluleLumineuseAssociee.toString());
            int w = this.getWidth(); 
            int h = this.getHeight(); 
            if (celluleLumineuseAssociee.estEteint() == true) { 
                g.setColor(Color.red); 
            } else { 
                g.setColor(Color.yellow); 
            } 
            g.fillOval(2, 2, w - 8, h - 4);
        }
    }
    
    

    private void afficherMessageVictoire() { // ouvre une fenetre de fin de partie
        FenetreVictoire f = new FenetreVictoire() ;
        f.setVisible(true) ;
        dispose();// enlève l'ancienne page 
    }
    
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);   
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Diag;
    private javax.swing.JPanel PanneauGrille;
    private javax.swing.JPanel PanneaudesColonnes;
    private javax.swing.JPanel PanneaudesLignes;
    private javax.swing.JButton btndiag1;
    private javax.swing.JButton btndiag2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
